require "core.theme.util"
require "core.theme.completion"
require "core.theme.colors"
require "core.theme.diagnostic"
require "core.theme.telescope"
require "core.theme.statusline"
require "core.theme.overwrite"
